name: ci

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches: 
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - run: dotnet build src/Neo4j.Berries.OGM -c Release
  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      Neo4j__Url: ${{ vars.NEO4J_URL }}
      Neo4j__Username: ${{ secrets.NEO4J_USERNAME }}
      Neo4j__Password: ${{ secrets.NEO4J_PASSWORD }}
      Neo4j__Database: githubTest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet test tests/Neo4j.Berries.OGM.Tests -c Release