# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ci/cd

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - run: dotnet build src/Neo4j.Berries.OGM -c Release
  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      Neo4j__Url: ${{ vars.NEO4J_URL }}
      Neo4j__Username: ${{ secrets.NEO4J_USERNAME }}
      Neo4j__Password: ${{ secrets.NEO4J_PASSWORD }}
      Neo4j__Database: githubTest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet test tests/Neo4j.Berries.OGM.Tests -c Release
  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/dev'
    env:
      PACKAGE_VERSION: 1.0.0-preview-${{ github.run_number }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet pack src/Neo4j.Berries.OGM -c Release /p:Version=$PACKAGE_VERSION
      - run: dotnet nuget push src/Neo4j.Berries.OGM/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_APIKEY }} --source https://api.nuget.org/v3/index.json
